TBScripts/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TBScripts.Models;
using TBScripts.DAL;

namespace TBScripts.Controllers
{
    public class BookController :  BaseController
    {

        private TreeViewDal objTreeViewDal;

        //
        // GET: /Book/
        public ActionResult AddBook(int ProdLineId, string Desc)
        {
            BookModel model = new BookModel();
            model.intProductLineId = ProdLineId;
            return View("AddBook", model);
        }

        public ActionResult AddBookDetails(string BookTitle, int BookType, int ProductLineId)
        {
            objTreeViewDal = new TreeViewDal();
            BookModel model = new BookModel();
            model.strBookTitle = BookTitle;
            model.intBookTypeId = BookType;
            model.intProductLineId = ProductLineId;

            objTreeViewDal.SetBooks(ref model);

            return View("AddBook", model);
        }
        //Edit Book
        public ActionResult EditBook(int lintBookId)
        {

            objTreeViewDal = new TreeViewDal();
            BookModel objBook = new BookModel();
            objBook.intBookId = (int)lintBookId;
            objTreeViewDal.GetBookByBookId(ref objBook);

            //getting Product Line 
            List<ProductLineModel> lstProductLine = new List<ProductLineModel>();
            lstProductLine = objTreeViewDal.GetProductLine();
            ViewData["ProductLine"] = lstProductLine;

            return View("EditBook", objBook);
        }
        //Getting List of Books
        public ActionResult BooksList()
        {
            return View();
        }

        public ActionResult UpdateBookDetails(int lintBookId, string BookName, DateTime? ChangesDeadline, DateTime? AnticipatedDate, DateTime? NotificationDate, DateTime? PublishedDate, int ProductLineId)
        {

            TreeViewDal objTreeViewDal = new TreeViewDal();
            BookModel objBook = new BookModel();
            objBook.intBookId = (int)lintBookId;
            objBook.strBookTitle = (string)BookName;
            objBook.ChangesDeadline = ChangesDeadline;
            objBook.AnticipatedPublishDate = AnticipatedDate;
            objBook.NotificationSentDate = NotificationDate;
            objBook.DatePublished = PublishedDate;
            objBook.intProductLineId = (int)ProductLineId;

            //Here needs write book update method
            objTreeViewDal.GetBookByBookId(ref objBook);

            //getting Product Line 
            List<ProductLineModel> lstProductLine = new List<ProductLineModel>();
            lstProductLine = objTreeViewDal.GetProductLine();
            ViewData["ProductLine"] = lstProductLine;

            return View("EditBook", objBook);
        }

        public ActionResult BookSections(int lintBookId)
        {

            objTreeViewDal = new TreeViewDal();
            SectionModel objSection = new SectionModel();
            List<SectionModel> lstSections = new List<SectionModel>();
            lstSections = objTreeViewDal.getSectionsByBookId(lintBookId);

            ////getting Product Line 
            //List<ProductLineModel> lstProductLine = new List<ProductLineModel>();
            //lstProductLine = objTreeViewDal.GetProductLine();
            //ViewData["ProductLine"] = lstProductLine;

            return View("BookSections", lstSections);
            //return View(lstSections);
        }

        public ActionResult AddSection(int? sectionid, string sectiontitle, int? sortseq)
        {
            SectionModel objSection = new SectionModel();
            objSection.SectionId = Convert.ToInt32(sectionid);
            if (sectiontitle != "" || sectiontitle != null)
                objSection.SectionTitle = sectiontitle.ToString();
            else
                objSection.SectionTitle = "";
            objSection.SortSequence = Convert.ToInt32(sortseq);
            return View("AddSection", objSection);
        }


        public ActionResult AddProductLine()
        {
            ProductModel model = new ProductModel();
            objTreeViewDal = new TreeViewDal();
            model.LstProductLineTypeModel = objTreeViewDal.GetProductLineTypeForDDl();
            return View("AddProductLine", model);
        }


        public ActionResult AddProductLine1(string ProductLineDesc, int ProductLineType, string Copyright)
        {
            objTreeViewDal = new TreeViewDal();
            ProductModel model = new ProductModel();
            model.strProductLineDesc = ProductLineDesc;
            model.intProductLineTypeId = ProductLineType;
            model.CopyrightDesc = Copyright;

            objTreeViewDal.SetProductLine(ref model);
            model.LstProductLineTypeModel = objTreeViewDal.GetProductLineTypeForDDl();
            if (model.intProductLineId > 0)
            {
                model.intProductLineTypeId = 0;
                model.strProductLineDesc = "";
                model.CopyrightDesc = "";
            }


            return View("AddProductLine", model);
        }


        [HttpPost]
        public ActionResult AddProductLine(ProductModel model)
        {
            objTreeViewDal = new TreeViewDal();
            objTreeViewDal.SetProductLine(ref model);
            model.LstProductLineTypeModel = objTreeViewDal.GetProductLineTypeForDDl();
            if (model.intProductLineId > 0)
            {
                model.intProductLineTypeId = 0;
                model.strProductLineDesc = "";
                model.CopyrightDesc = "";
            }


            return View("AddProductLine", model);
        }



        //    public ActionResult AddBookWithParam(int ProdLineId, string Desc)
        //  //  public ActionResult AddBookWithParam()    
        //{
        //        BookModel model = new BookModel();

        //        model.strBookTitle = "test mm";
        //        model.intBookId = 1;
        //        return View("AddBookWithParam",model);
        //    }
    }
}

TBScripts/Views/Book/AddBook.cshtml
@model TBScripts.Models.BookModel
@{
    Layout = null;
}

<!--<script src="~/Scripts/jquery-1.10.2.min.js"></script>-->

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
@*<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>*@

<link href="~/Content/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link href="~/Content/css/tbcustom2.css" rel="stylesheet" media="screen">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">


<script type="text/javascript">
    $(document).ready(function () {


        $('.closediALOGUEBOX').click(function () {
            alert('vcv');
            $("#dialog-edit").dialog('close');
        });

        $("#btnSave1").on("click", function (e) {
            var serviceURL = ""
            var serviceURL = "/Book/AddBookDetails";

            alert("serviceURL");

            var BookTitleValue = $("#strBookTitle").val();
            // alert(ProductLineDesc);
            var BookTypeValue = $("#selBookType").val();
            //alert(ProductLineType);
            var ProductLineIdValue = $("#intProductLineId").val();


            if (BookTitleValue == '' || BookTitleValue == null) {
                alert('Please Book Title');
                return false;
            }


            $.ajax({
                type: "POST",
                url: serviceURL,
                data: { BookTitle: BookTitleValue, BookType: BookTypeValue, ProductLineId: ProductLineIdValue }
            }).done(function (data) {
                successFunc(data, status);

            });


            function successFunc(data, status) {
                alert("Product line added successfully");
                $("#strBookTitle").val('');
            }

            function errorFunc() {
                alert('error');
            }
        });
    });
</script>

<div>

    @*<input type="text" value=@Model.strBookTitle />
        @Html.TextBoxFor(m => m.strBookTitle, Model.strBookTitle)*@

    <div style="clear:both"></div>
    <div class="content1">
        <div class="content1-sub">
            <span>Book TItle:</span>
        </div>
        <div style="float:left;width:40%">
            @Html.TextBoxFor(m => m.strBookTitle, Model.strBookTitle)
            @Html.TextBoxFor(m => m.intProductLineId, Model.intProductLineId)

        </div>
    </div>

    <div style="clear:both"></div>
    <div class="content1">
        <div class="content1-sub">
            <span>Book Type:</span>
        </div>
        <div style="float:left;width:40%">
            @*@Html.TextBoxFor(m => m.intBookTypeId, Model.strBookTitle)*@

            <select id="selBookType" name="selBookType">
                <option value="">Plese Select</option>
                <option value="1">Type1</option>
            </select>

        </div>
    </div>
    <div style="clear:both"></div>

    <div class="content1">
        <div class="content1-sub">
            &nbsp;
        </div>
        <div style="float:left;width:40%">
            <input type="button" value="Save" id="btnSave1" name="btnSave1" class="btn btn-primary" /> &nbsp;
            @*<input type="button" value="Cancel" id="btnCancel" name="btnCancel" class="btn btn-primary closediALOGUEBOX" />*@
            @*<input type="button" value="Cancel" id="btnCancel" name="btnCancel" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ui-dialog-titlebar-close btn btn-primary closediALOGUEBOX" />*@
        </div>
    </div>


    @*<div style="width:500px;">
            @Html.Grid(Model).Columns(columns =>
                        {
                            columns.Add(c => c.Id).Titled("Client ID");
                            columns.Add(c => c.Name).Titled("Name").Filterable(true);
                            columns.Add(c => c.Email).Titled("Email");
                        }).WithPaging(3).Sortable(true)
        </div>*@



</div>

TBScripts/Views/Book/AddBookWithParam.cshtml
@model TBScripts.Models.BookModel


<div>
   with param
    <input type="text" value=@Model.strBookTitle />

</div>

TBScripts/Views/Book/AddProductLine.cshtml
@model TBScripts.Models.ProductModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddProductLine</title>

    <script type="text/javascript">
        function save_product_line() {
            var serviceURL = ""
            var serviceURL = "/Book/AddProductLine1";
           // alert(serviceURL);

            var ProductLineDesc = $("#strProductLineDesc").val();
           // alert(ProductLineDesc);
            var ProductLineType = $("#intProductLineTypeId").val();
            //alert(ProductLineType);
            var Copyright = $("#CopyrightDesc").val();


            if (ProductLineDesc == '' || ProductLineDesc == null)
            {
                alert('Plenter ProductLineDesc vzlue');
                return false;
            }
                

            // alert(modelDataJSON);

            $.ajax({
                type: "POST",
                url: serviceURL,
                data: { ProductLineDesc: ProductLineDesc, ProductLineType: ProductLineType, Copyright: Copyright}
            }).done(function (data) {
                successFunc(data, status);
           
            });

            //$.ajax({
            //    type: "POST",
            //    url: serviceURL,

            //    data: { ProductLineDesc: "master" ,ProductLineType:1,Copyright:"jim"},

            //    contentType: "application/json; charset=utf-8",
            //    dataType: 'json',
            //    success: successFunc,
            //    error: errorFunc
            //});

            function successFunc(data, status) {
                alert("Product line added successfully");
                $("#strProductLineDesc").val('');
                $("#CopyrightDesc").val('');

            }

            function errorFunc() {
                alert('error');
            }
        }
    </script>

</head>
<body>
    <div>
        @using (Html.BeginForm())
        {
            <div style="clear:both"></div>
            <div class="content1">
                <div style="float:left;width:40%">
                    <span>Product Line Desc:</span>
                </div>
                <div style="float:left;width:40%">
                    @Html.TextBoxFor(m => m.strProductLineDesc)
                </div>
            </div>

            <div style="clear:both"></div>
            <div class="content1">
                <div style="float:left;width:40%">
                    <span>Product Line Type:</span>
                </div>
                <div style="float:left;width:40%">
                    @Html.DropDownListFor(m => m.intProductLineTypeId, Model.ProductLineTypeItems)
                </div>
            </div>

            <div style="clear:both"></div>
            <div class="content1">
                <div style="float:left;width:40%">
                    <span>Copyright (©):</span>
                </div>
                <div style="float:left;width:40%">
                    @Html.TextBoxFor(m => m.CopyrightDesc)
                </div>
            </div>

            <div class="content1">
                <div class="content1-sub">
                    &nbsp;
                </div>
                <div style="float:left;width:40%">
                    <input onclick="save_product_line();" type="button" value="Save" class="btn btn-primary" /> &nbsp;
                    <input onclick="$('#dialog-edit').dialog('close');" type="button" value="Cancel" id="btnCancel" name="btnCancel" class="btn btn-primary" />
                </div>
            </div>

        }
    </div>
</body>
</html>

TBScripts/Views/Book/AddSection.cshtml
@model TBScripts.Models.SectionModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddSection</title>

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/css/tbcustom2.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
   

</head>
<body>
    <div>

        <div style="clear:both"></div>
        <div class="content1">
            <div style="float:left;width:40%">
                <span>Section Title:</span>
            </div>
            <div style="float:left;width:40%">
                @Html.TextBoxFor(m => m.SectionTitle)
                @Html.TextBoxFor(m => m.SectionId)
            </div>
        </div>

        <div style="clear:both"></div>
        <div class="content1">
            <div style="float:left;width:40%">
                <span>Sort Sequence:</span>
            </div>
            <div style="float:left;width:40%">
                @Html.TextBoxFor(m => m.SortSequence)
            </div>
        </div>

        <div class="content1">
            <div class="content1-sub">
                &nbsp;
            </div>
            <div style="float:left;width:40%">
                @*onclick="save_product_line();"*@
                <input type="button" value="Save" class="btn btn-primary" /> &nbsp;
                <input onclick="$('#dialog-edit').dialog('close');" type="button" value="Cancel" id="btnCancel" name="btnCancel" class="btn btn-primary" />
            </div>
        </div>

    </div>
</body>
</html>

TBScripts/Views/Book/BookSections.cshtml
@model IList<TBScripts.Models.SectionModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BookSections</title>
    @*<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
        <script src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
        <link href="cdn.datatables.net/1.10.2/css/jquery.dataTables.css" rel="stylesheet" media="screen">*@

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/css/tbcustom2.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">




    <link href="@Url.Content("~/JsTableSorter/theme.blue.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/JsTableSorter/jquery.tablesorter.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/JsTableSorter/jquery.tablesorter.pager.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/JsTableSorter/jquery.tablesorter.widgets.js")" type="text/javascript"></script>

    <script type="text/javascript">
        //$(document).ready(function () {
        //    $('#example').dataTable();
        //});
        var url = "";
        var Mytitle = 'Section'
        //alert(Mytitle);
        $("#dialog-edit").dialog({
            title: Mytitle,
            autoOpen: false,
            resizable: false,
            height: 455,
            width: 550,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {

                alert($(this).data("URL"));
                url = $(this).data("URL");
                //var dlgData = $("#dialog-edit").data("myData");
                //alert(dlgData.data1);
                $(this).load(url);

            },
            close: function (event, ui) {
                $(this).dialog('close');
            }
        });





        function editbook(sectionid, sectionname, sortseq) {

            var url = "/Book/AddSection?sectionid=" + encodeURI(sectionid) + "&sectiontitle=" + encodeURI(sectionname) + "&sortseq=" + encodeURI(sortseq);
            $("#dialog-edit").data("URL", url).dialog('open');

            //alert("sudhakar");
            //alert(sectionid);
            //alert(sectionname);
            //var s = "sudhakar polisetti";
            //alert(s);
            //var url = "/Book/AddSection?sectionid=" + sectionid + "&sectiontitle='" + sectionname + "'&sortseq=" + sortseq;
            //var url = "/Book/AddSection?sectionid=" + encodeURI(sectionid) + "&sectiontitle=" + encodeURI(sectionname) + "&sortseq=" + encodeURI(sortseq);
          
            //var url = "/Book/AddSection?sectionid=10&sectiontitle=sudhakar%20%polisetti";
            //alert(url);

            // Mytitle = 'Edit Section';
            //alert(Mytitle);
            //$("#dialog-edit").dialog('close');
            //$("#dialog-edit").data("sectionid", sectionid).dialog('open');
            // $("#dialog-edit").data("myData", { data1: "Hello", data2: "world" }).dialog('open');
            
            //$("#dialog-edit").dialog('open');

            //$("#dialog-edit").dialog({
            //    open: function () {
            //        $(this).dialog("option", "title", "My new title");
            //    }
            //})

            return false;
        }

        $(document).ready(function ($) {
            //  alert('hi');
            $('#example').tablesorter({
                theme: 'blue',
                widthFixed: true,
                // widgets: ['filter']
            }).tablesorterPager({
                // target the pager markup - see the HTML block below
                container: $("#pager"),

                // output string - default is '{page}/{totalPages}';
                // possible variables:
                // {page}, {totalPages}, {startRow}, {endRow} and {totalRows}
                output: '{startRow} to {endRow} ({totalRows})',

                // apply disabled classname to the pager arrows when
                // the rows at either extreme is visible - default is true
                updateArrows: true,

                // remove rows from the table to speed up the sort of large
                // tables. setting this to false, only hides the non-visible rows;
                // needed if you plan to add/remove rows with the pager enabled.
                removeRows: false

            });

            //$("#example").tablesorter({ widthFixed: true, widgets: ['zebra'] }).tablesorterPager({ container: $("#pager") });


        });

    </script>
</head>
<body>


    <div id="dialog-edit" style="display: none">
    </div>

    <div>
        Displying sections.............
        <table id="example" class="display" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th></th>
                    <th>Section Id</th>
                    <th>Section Name</th>
                    <th>Sort Sequence</th>

                </tr>
            </thead>

            <tfoot>
                <tr>
                    <th></th>
                    <th>Section Id</th>
                    <th>Section Name</th>
                    <th>Sort Sequence</th>
                </tr>
            </tfoot>

            <tbody>
                @*<tr>
                        <td>Tiger Nixon</td>
                        <td>System Architect</td>
                        <td>Edinburgh</td>
                        <td>61</td>
                        <td>2011/04/25</td>
                        <td>$320,800</td>
                    </tr>  *@

                @foreach (var obj in Model)
                {
                    <tr>
                        <td>
                            <img src="~/Content/pic/images/icon_edit.gif" onclick="editbook('@obj.SectionId','@obj.SectionTitle','@obj.SortSequence');" style="cursor:pointer;" />
                            <img src="~/Content/pic/images/icon_delete.gif" style="cursor:pointer;" />
                        </td>
                        <td>@obj.SectionId</td>
                        <td>@obj.SectionTitle</td>
                        <td>@obj.SortSequence</td>

                    </tr>
                }

            </tbody>


        </table>

        <div id="pager" class="pager">
            <form>
                <img src="http://mottie.github.com/tablesorter/addons/pager/icons/first.png" class="first" />
                <img src="http://mottie.github.com/tablesorter/addons/pager/icons/prev.png" class="prev" />
                <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
                <img src="http://mottie.github.com/tablesorter/addons/pager/icons/next.png" class="next" />
                <img src="http://mottie.github.com/tablesorter/addons/pager/icons/last.png" class="last" />
                <select class="pagesize">
                    <option selected="selected" value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="40">40</option>
                </select>
            </form>
        </div>

    </div>
</body>
</html>

TBScripts/Views/Book/BooksList.cshtml
@using TBScripts.Models;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BooksList</title>
</head>
<body>
    <div>
        <b>
            @*@Html.ActionLink("Add Book", "AddBook", "Book", new { ProdLineId = Model.ProductModel.intProductLineId, Desc = "Teaching Book" }, new { id = "AddBook", @class = "myCssClass" })*@
            @*<a id="AddBook" href="~/Book/AddBook?ProdLineId=1&Desc='Teaching Book'">Add Book</a>*@
            @*<a id="AddBook" href="~/Book/AddBookWithParam">Add Book</a>*@
        </b>
        @{
            List<TreeViewModel> t = new List<TreeViewModel>();
            if (TempData["BooksItems"] != null)
            {
                t = (List<TreeViewModel>)TempData["BooksItems"];
            }
            if (t.Count > 0)
            {
                <table border="0" cellpadding="4" cellspacing="2">
                    <tr><th>&nbsp;</th><th>Book Id</th><th>Book Title</th><th>Book Type</th></tr>
                    @foreach (var b in t)
                    {
                        <tr>
                            <td>
                                <img src="~/Content/pic/images/icon_edit.gif" />
                                <img src="~/Content/pic/images/icon_delete.gif" />
                            </td>
                            <td>@b.intBookId</td>
                            <td>@b.strBookTitle</td>
                            <td>
                                <select id="selBookType" name="selBookType">
                                    <option value="">Plese Select</option>
                                    <option value="1">Type1</option>
                                </select>
                            </td>

                        </tr>
                    }
                </table>
            }
        }
    </div>
</body>
</html>