TBScripts/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TBScripts.DAL;
using TBScripts.Models;

namespace TBScripts.Controllers
{
    public class ReportController : BaseController
    {
        //
        // GET: /Report/
        public ActionResult Index()
        {
            return View();
        }

        public List<PreNotifyListModel> GetNotificationReport(int BookList)
        {

            ReportListModel reports = new ReportListModel();
            PreNotifyListModel objTreeView = new PreNotifyListModel();
            List<PreNotifyListModel> PreNotifyList = new List<PreNotifyListModel>();
            TreeViewDal objTreeViewDal = new TreeViewDal();

            PreNotifyList = objTreeViewDal.GetPreNotifyReportByBookId(BookList);

            if (PreNotifyList.Count > 0)
            {
                foreach (var item in PreNotifyList)
                {
                    //get files per sections
                    item.FileStatus = objTreeViewDal.GetFileStausBySectionId(item.SectionId);
                }
            }

            //model.treeViewModel = lstTreeView;

            //TreeViewModel objTreeView1 = new TreeViewModel();
            //List<TreeViewModel> lstTreeView1 = new List<TreeViewModel>();
            //lstTreeView1 = objTreeViewDal.GetTreeView();


            //int lintPrvBookId = 0;
            //List<TreeViewModel> t = new List<TreeViewModel>();
            //foreach (var book in lstTreeView1)
            //{
            //    if (book.intBookId != lintPrvBookId)
            //    {
            //        t.Add(book);
            //    }
            //    lintPrvBookId = book.intBookId;
            //}

            //TempData["BooksItems"] = t;

            return PreNotifyList;// View(reports);

            //return Json("Sucess");
        }

        public ActionResult PreNotifications()
        {

            List<TBScripts.Models.BookModel> Books = new List<TBScripts.Models.BookModel>();
            ReportListModel reports = new ReportListModel();
            try
            {

                using (TBScripts.DAL.PHdataConnectionString1 DBContext = new TBScripts.DAL.PHdataConnectionString1())
                {
                    Books = DBContext.Books.Select(x => new BookModel
                    {
                        strBookTitle = x.BookTitle,
                        intBookId = x.BookId
                    }).ToList();

                    reports.BookList = new SelectList(Books, "intBookId", "strBookTitle");



                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View(reports);

            //  return View();
        }
        [HttpPost]
        public ActionResult PreNotifications(int BookList)
        {

            List<TBScripts.Models.BookModel> Books = new List<TBScripts.Models.BookModel>();
            ReportListModel reports = new ReportListModel();
            try
            {

                using (TBScripts.DAL.PHdataConnectionString1 DBContext = new TBScripts.DAL.PHdataConnectionString1())
                {
                    Books = DBContext.Books.Select(x => new BookModel
                    {
                        strBookTitle = x.BookTitle,
                        intBookId = x.BookId
                    }).ToList();

                    reports.BookList = new SelectList(Books, "intBookId", "strBookTitle");



                }
                reports.PreNotifyList = GetNotificationReport(BookList);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View(reports);

            //  return View();
        }



        public ActionResult SiteUsage()
        {
            return View();
        }

        public ActionResult Content()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PreNotifications1(int? lintBookId)
        {
            Mymodel model = new Mymodel();
            TreeViewModel objTreeView = new TreeViewModel();
            List<TreeViewModel> lstTreeView = new List<TreeViewModel>();
            TreeViewDal objTreeViewDal = new TreeViewDal();

            lstTreeView = objTreeViewDal.GetTreeViewByBookId(lintBookId);
            model.treeViewModel = lstTreeView;

            TreeViewModel objTreeView1 = new TreeViewModel();
            List<TreeViewModel> lstTreeView1 = new List<TreeViewModel>();
            lstTreeView1 = objTreeViewDal.GetTreeView();


            int lintPrvBookId = 0;
            List<TreeViewModel> t = new List<TreeViewModel>();
            foreach (var book in lstTreeView1)
            {
                if (book.intBookId != lintPrvBookId)
                {
                    t.Add(book);
                }
                lintPrvBookId = book.intBookId;
            }

            TempData["BooksItems"] = t;

            return View(model);
        }

        public PartialViewResult ChaptersBySectionID(int SectionId)
        {
            List<SectionChapters> lstTreeView = new List<SectionChapters>();
            TreeViewDal objTreeViewDal = new TreeViewDal();
            lstTreeView = objTreeViewDal.GetChaptersBySectionID(SectionId);
            return PartialView("_PartialChapters", lstTreeView);
        }

        public PartialViewResult HandoutsByChapterID(int ChapterId)
        {
            List<ChapterHandOuts> lstTreeView = new List<ChapterHandOuts>();
            TreeViewDal objTreeViewDal = new TreeViewDal();
            lstTreeView = objTreeViewDal.GetHandoutsByChapterID(ChapterId);
            return PartialView("_PartialHandouts", lstTreeView);
        }

        /* Total usage report */
        [HttpPost]
        public PartialViewResult GetTotalUsage(int SiteList, int Languages, string StartDate, string EndDate)
        {

            try
            {
                TotalUsageStatusReport t = new TotalUsageStatusReport();
                List<HandoutCounts> counts = new List<HandoutCounts>();
                TreeViewDal objTreeViewDal = new TreeViewDal();

                if (StartDate == null)
                    StartDate = "";
                if (EndDate == null)
                    EndDate = "";

                counts = objTreeViewDal.GetTotalUsageReport(SiteList, Languages, StartDate, EndDate);

                //HandoutCounts count = new HandoutCounts();
                //count.HandoutId = 1;
                //count.HandoutTitle = "fdfsdfsd";
                //count.ViewsCount = 10;
                //count.PrintCounts = 4;
                //counts.Add(count);
                t.HandoutCounts = counts;


                return PartialView("_TotalUsageReportPartial", t);
            }
            catch (Exception ex)
            {
                
                throw ex;
            }
        }

        public ActionResult TotalUsage()
        {
            List<TBScripts.Models.SiteReport> Sites = new List<TBScripts.Models.SiteReport>();
            List<TBScripts.Models.LanguageModel> Languages = new List<TBScripts.Models.LanguageModel>();
            TotalUsageStatusReport reports = new TotalUsageStatusReport();
            try
            {

                using (TBScripts.DAL.PHdataConnectionString1 DBContext = new TBScripts.DAL.PHdataConnectionString1())
                {
                    Sites = DBContext.Sites.Select(x => new SiteReport
                    {
                        SiteId = x.SiteId,
                        SiteTitle = x.SiteName
                    }).ToList();

                    reports.SiteList = new SelectList(Sites, "SiteId", "SiteTitle");

                    Languages = DBContext.Languages.Select(x => new LanguageModel
                    {
                        intlanguageId = x.LanguageId,
                        strlanguageName = x.LanguageName
                    }).ToList();

                    reports.Languages = new SelectList(Languages, "intlanguageId", "strlanguageName");

                }



            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View(reports);
        }


    }
}

TBScripts/Views/Report/Content.cshtml
@{
    ViewBag.Title = "Content";
    Layout = "~/Views/Shared/_TBMainLayout.cshtml";
}



<body>

    @Html.Partial("~/Views/Report/_TBReportLayout.cshtml")

    <div id="partialView">

        <div class="col-med-5 col-lg-9 row main-right">
            <div class="panel panel-default systemAdminDiv">

                @*@ViewBag.EmpMessage*@
            Contents


            </div>
        </div>
    </div>
</body>

TBScripts/Views/Report/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TBMainLayout.cshtml";
}




<body>

    @Html.Partial("~/Views/Report/_TBReportLayout.cshtml")

    <div id="partialView">

        <div class="col-med-5 col-lg-9 row main-right">
            <div class="panel panel-default systemAdminDiv">

                @*@ViewBag.EmpMessage*@
                Welcome to Reports


            </div>
        </div>
    </div>
</body>

TBScripts/Views/Report/PreNotifications.cshtml
@model TBScripts.Models.ReportListModel

@{
    ViewBag.Title = "PreNotifications";
    Layout = "~/Views/Shared/_TBMainLayout.cshtml";
}



<style>
    .treeview ul { /*CSS for Simple Tree Menu*/
        margin: 0;
        padding: 0;
    }

    .treeview li { /*Style for LI elements in general (excludes an LI that contains sub lists)*/
        background: white url("../Images/minus.png") no-repeat left center;
        list-style-type: none;
        padding-left: 22px;
        margin-bottom: 3px;
        background-size: 15px;
    }

        .treeview li.submenu { /* Style for LI that contains sub lists (other ULs). */
            background: white url("../Images/plus.png") no-repeat left 1px;
            cursor: hand !important;
            cursor: pointer !important;
            background-size: 15px;
        }


            .treeview li.submenu ul { /*Style for ULs that are children of LIs (submenu) */
                display: none; /*Hide them by default. Don't delete. */
            }

    .treeview .submenu ul li { /*Style for LIs of ULs that are children of LIs (submenu) */
        cursor: default;
    }
</style>


<body>
    @Html.Partial("~/Views/Report/_TBReportLayout.cshtml")
    <div id="partialView">
        <div class="col-med-5 col-lg-9 row main-right">
            <div class="panel panel-default systemAdminDiv">
                @*@ViewBag.EmpMessage*@
                @*Notifications*@

                @*@using (Ajax.BeginForm("GetNotificationReport", "Report", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnSuccess = "SaveUser", LoadingElementId = "loader" }, new { id = "frmPerson123" }))*@
                @using (Html.BeginForm())
                {
                    <div class="form-horizontal">
                        Reports
                        <hr />



                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-2">
                                        @Html.Label("Choose Book", htmlAttributes: new { @class = "control-label " })

                                    </div>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(model => model.BookList, new SelectList(Model.BookList, "Value", "Text"), null, new { @class = "form-control" })
                                    </div>

                                    <div class="col-md-2">
                                        <input type="submit" value="Go" class="btn btn-primary" id="btnSaveEmployee" />  @*onclick="SaveEmployee()"*@
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div>

                            @*<ul id="treemenu1" class="treeview">

                                    <li>
                                        Folder 1
                                        <ul>
                                            <li>
                                                Sub Item 1.1
                                                <ul>
                                                    <li>
                                                        Sub Item 1.2
                                                        <ul>
                                                            <li>Sub Item 1.2.1</li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>Sub Item none</li>
                                        </ul>
                                    </li>
                                </ul>*@



                            @if (Model.PreNotifyList != null)
                            {
                                int lBookId = 0;
                                int lSectionId = 0;
                                int lChapterId = 0;
                                <ul>
                                    <li>


                                        @foreach (var item in Model.PreNotifyList)
                                        {
                                            int lNewBookId = item.BookId;
                                            int lNewSectionId = item.SectionId;
                                            bool bHasSections = false;
                                            int lNewChapterId = item.ChapterId;
                                            int lNewHandoutId = item.HandoutId;
                                            if (lNewBookId != lBookId && lNewBookId > 0)
                                            {
                                                lBookId = lNewBookId;
                                                @*<span>Book----</span>*@
                                                <img src="~/Images/tree/book.gif" />@item.BookTitle
                                            }
                                            if (lNewSectionId > 0)
                                            {
                                                <ul id="treemenu1" class="treeview">
                                                    @if (lNewSectionId != lSectionId && lNewSectionId > 0)
                                                    {
                                                        lSectionId = lNewSectionId;
                                                        <li>
                                                            @*<span>Section----</span>*@
                                                            <img src="~/Images/TreeIcons/Icons/xpFolder.gif" />@item.SectionTitle


                                                            @if (item.FileStatus.Count > 0)
                                                            {
                                                                <ul>
                                                                    @foreach (var file in item.FileStatus)
                                                                    {
                                                                        <li>
                                                                            @*<span>File----</span>*@
                                                                            <img src="~/Images/TreeIcons/Icons/database.gif" />@file.Name

                                                                            @if (file.status == 1)
                                                                            {
                                                                                <span>--Uploaded</span>

                                                                            }
                                                                            else if (file.status == 2)
                                                                            {
                                                                                <span>--Published</span>

                                                                            }
                                                                            else if (file.status == 3)
                                                                            {
                                                                                <span>--Archived</span>

                                                                            }
                                                                            else if (file.status == 4)
                                                                            {
                                                                                <span>--Removed</span>

                                                                            }
                                                                        </li>

                                                                    }
                                                                </ul>
                                                            }

                                                            @if (lNewChapterId > 0)
                                                            {
                                                                //call chapaters partial view
                                                                //Html.Partial("_PartialChapters");
                                                                //CreateChapterNode(lNewChapterId, sNewChapterDesc, lBookId, "bk_");
                                                                Html.RenderAction("ChaptersBySectionID", new { @SectionId = item.SectionId });
                                                            }
                                                        </li>
                                                    }
                                                </ul>
                                            }

                                        }
                                    </li>
                                </ul>
                            }

                        </div>

                    </div>
                }
            </div>
        </div>
    </div>
</body>


<script src="~/Scripts/simpletreemenu.js"></script>
<script type="text/javascript">
    //ddtreemenu.createTree(treeid, enablepersist, opt_persist_in_days (default is 1))
    ddtreemenu.createTree("treemenu1", true)
    ddtreemenu.createTree("treemenu2", false)
</script>

TBScripts/Views/Report/SiteUsage.cshtml
@{
    ViewBag.Title = "SiteUsage";
    Layout = "~/Views/Shared/_TBMainLayout.cshtml";
}

<body>

    @Html.Partial("~/Views/Report/_TBReportLayout.cshtml")

    <div id="partialView">

        <div class="col-med-5 col-lg-9 row main-right">
            <div class="panel panel-default systemAdminDiv">

                @*@ViewBag.EmpMessage*@
               site usage


            </div>
        </div>
    </div>
</body>

TBScripts/Views/Report/TotalUsage.cshtml
@model TBScripts.Models.TotalUsageStatusReport

@{
    ViewBag.Title = "TotalUsage";
    Layout = "~/Views/Shared/_TBMainLayout.cshtml";
}

<body>
    @Html.Partial("~/Views/Report/_TBReportLayout.cshtml")
    <div id="partialView">
        <div class="col-med-5 col-lg-9 row main-right">
            <div class="panel panel-default systemAdminDiv">

                @*@using (Html.BeginForm())*@
                @using (Ajax.BeginForm("GetTotalUsage", "Report", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnSuccess = "ReportResponse", LoadingElementId = "loader", UpdateTargetId = "divUpdate" }, new { id = "frmPerson123" }))
                {

                  
                    <div class="form-horizontal">
                        Total Usage Report
                        <hr />

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-3">
                                        @Html.Label("Site Name", htmlAttributes: new { @class = "control-label " })
                                    </div>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(model => model.SiteList, new SelectList(Model.SiteList, "Value", "Text"), null, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-3">
                                        @Html.Label("Language", htmlAttributes: new { @class = "control-label " })
                                    </div>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(model => model.Languages, new SelectList(Model.Languages, "Value", "Text"), null, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-3">
                                        @Html.Label("Start Date", htmlAttributes: new { @class = "control-label " })
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(model => model.StartDate, htmlAttributes: new { @class = "form-control", type = "date"  })

                                        @*@Html.TextBox(Model.StartDate.ToShortDateString(), String.Format("{0:d}", Model.StartDate.ToShortDateString()),
                                         new { @class = "form-control", type = "date" })*@





                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-3">
                                        @Html.Label("End Date", htmlAttributes: new { @class = "control-label " })
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(model => model.EndDate, htmlAttributes: new { @class = "form-control", type = "date" })

                                        @*@Html.TextBox(Model.EndDate.ToShortDateString(), String.Format("{0:d}", Model.EndDate.ToShortDateString()),
                                         new { @class = "form-control", type = "date" })*@

                                    </div>
                                    <div class="col-md-2">
                                        <input type="submit" value="Go" class="btn btn-primary" id="btnSaveEmployee" />  @*onclick="SaveEmployee()"*@
                                    </div>
                                </div>
                            </div>
                        </div>





                    </div>
                    
                      <div id="divUpdate">
                      
                        @*@if(Model.HandoutCounts != null)
                        {
                            if(Model.HandoutCounts.Count > 0)
                            {
                              <div>sudhakar</div>
                                Html.RenderPartial("_TotalUsageReportPartial");
                            
                            }
                        }*@
                    </div>


                }
            </div>
        </div>
    </div>
</body>



<script type="text/javascript">
    //$(document).ready(function () {
    //    $('input[type=datetime]').datepicker({
    //        dateFormat: "dd/M/yy",
    //        changeMonth: true,
    //        changeYear: true,
    //        yearRange: "-60:+0"
    //    });

    //});

    $(function () {
        $(".datefield").datepicker();
    });

    function ReportResponse(response) {
        debugger;
        //var message = "Person Id: " + response.PersonId;
        //message += "\nName: " + response.Name;
        //message += "\nGender: " + response.Gender;
        //message += "\nCity: " + response.City;
        //alert("ReportResponse");
    }


</script> 

TBScripts/Views/Report/_PartialChapters.cshtml
@model IEnumerable<TBScripts.Models.SectionChapters>

@*@foreach (var treeNode in Model)
    {
        <ul>
            @if (treeNode != null)
            {
                <li>
                    <a href="#">
                        @treeNode.NodeName
                    </a>
                    @if (treeNode.ChildNode.Count > 0)
                    {
                        @Html.Partial("ChildNode", treeNode.ChildNode)
                    }
                </li>
            }
        </ul>
    }*@

@foreach (var treeNode in Model)
{
    <ul>
        @if (treeNode != null)
        {
            <li>

                <img src="~/Images/TreeIcons/Icons/xpMyDoc.gif" /> @treeNode.ChapterTitle
               @{Html.RenderAction("HandoutsByChapterID", new { ChapterId = treeNode.ChapterId });}
                @*@Html.Partial("_PartialHandouts")*@
            </li>
          
        }
    </ul>
}

TBScripts/Views/Report/_PartialHandouts.cshtml
@model IEnumerable<TBScripts.Models.ChapterHandOuts>

@foreach (var treeNode in Model)
{
    <ul>
        @if (treeNode != null)
        {
            <li>

                <img src="~/Images/TreeIcons/Icons/page.gif" />@treeNode.HandoutTitle
              
            </li>

        }
    </ul>
}

TBScripts/Views/Report/_TBReportLayout.cshtml
<div class="col-med-2 col-lg-2 navtree" style="min-height:500px;">

    <div class="list-group">

        @*@Model.siteId*@


        <a class="list-group-item" href="~/Report/PreNotifications">
           
            <span class="glyphicon glyphicon-book"></span>Pre-Notification<span class="badge"></span>
        </a>

        <a class="list-group-item" href="~/Report/TotalUsage">

            <span class="glyphicon glyphicon-file"></span> Total Usage Stats
        </a>

        <a href="~/Report/SiteUsage" class="list-group-item">
            <span class="glyphicon glyphicon-book"></span> Site Usage Stats<span class="badge"></span>
        </a>



        <a class="list-group-item" href="~/Report/Content">

            <span class="glyphicon glyphicon-file"></span>Content Freshness
        </a>




    </div>
</div>

<script>
    $("#btnSubmit").click(function () {
        $("#divLoader").show();
        $.ajax
        ({
            url: '/Test/Submit',
            dataType: "json",
            type: "POST",
            contentType: 'application/json; charset=utf-8',
            data: {},
            //async: true,
            //processData: false,
            // cache: false,
            success: function (data) {
                $("#divLoader").hide();
                alert(data);
            },
            error: function (xhr) {
                $("#divLoader").hide();
                alert('error');
            }
        })
    });
</script>