TBScripts/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TBScripts.Models;
using TBScripts.DAL;

namespace TBScripts.Controllers
{
    public class BookController :  BaseController
    {

        private TreeViewDal objTreeViewDal;

        //
        // GET: /Book/
        public ActionResult AddBook(int ProdLineId, string Desc)
        {
            BookModel model = new BookModel();
            model.intProductLineId = ProdLineId;
            return View("AddBook", model);
        }

        public ActionResult AddBookDetails(string BookTitle, int BookType, int ProductLineId)
        {
            objTreeViewDal = new TreeViewDal();
            BookModel model = new BookModel();
            model.strBookTitle = BookTitle;
            model.intBookTypeId = BookType;
            model.intProductLineId = ProductLineId;

            objTreeViewDal.SetBooks(ref model);

            return View("AddBook", model);
        }
        //Edit Book
        public ActionResult EditBook(int lintBookId)
        {

            objTreeViewDal = new TreeViewDal();
            BookModel objBook = new BookModel();
            objBook.intBookId = (int)lintBookId;
            objTreeViewDal.GetBookByBookId(ref objBook);

            //getting Product Line 
            List<ProductLineModel> lstProductLine = new List<ProductLineModel>();
            lstProductLine = objTreeViewDal.GetProductLine();
            ViewData["ProductLine"] = lstProductLine;

            return View("EditBook", objBook);
        }
        //Getting List of Books
        public ActionResult BooksList()
        {
            return View();
        }

        public ActionResult UpdateBookDetails(int lintBookId, string BookName, DateTime? ChangesDeadline, DateTime? AnticipatedDate, DateTime? NotificationDate, DateTime? PublishedDate, int ProductLineId)
        {

            TreeViewDal objTreeViewDal = new TreeViewDal();
            BookModel objBook = new BookModel();
            objBook.intBookId = (int)lintBookId;
            objBook.strBookTitle = (string)BookName;
            objBook.ChangesDeadline = ChangesDeadline;
            objBook.AnticipatedPublishDate = AnticipatedDate;
            objBook.NotificationSentDate = NotificationDate;
            objBook.DatePublished = PublishedDate;
            objBook.intProductLineId = (int)ProductLineId;

            //Here needs write book update method
            objTreeViewDal.GetBookByBookId(ref objBook);

            //getting Product Line 
            List<ProductLineModel> lstProductLine = new List<ProductLineModel>();
            lstProductLine = objTreeViewDal.GetProductLine();
            ViewData["ProductLine"] = lstProductLine;

            return View("EditBook", objBook);
        }

        public ActionResult BookSections(int lintBookId)
        {

            objTreeViewDal = new TreeViewDal();
            SectionModel objSection = new SectionModel();
            List<SectionModel> lstSections = new List<SectionModel>();
            lstSections = objTreeViewDal.getSectionsByBookId(lintBookId);

            ////getting Product Line 
            //List<ProductLineModel> lstProductLine = new List<ProductLineModel>();
            //lstProductLine = objTreeViewDal.GetProductLine();
            //ViewData["ProductLine"] = lstProductLine;

            return View("BookSections", lstSections);
            //return View(lstSections);
        }

        public ActionResult AddSection(int? sectionid, string sectiontitle, int? sortseq)
        {
            SectionModel objSection = new SectionModel();
            objSection.SectionId = Convert.ToInt32(sectionid);
            if (sectiontitle != "" || sectiontitle != null)
                objSection.SectionTitle = sectiontitle.ToString();
            else
                objSection.SectionTitle = "";
            objSection.SortSequence = Convert.ToInt32(sortseq);
            return View("AddSection", objSection);
        }


        public ActionResult AddProductLine()
        {
            ProductModel model = new ProductModel();
            objTreeViewDal = new TreeViewDal();
            model.LstProductLineTypeModel = objTreeViewDal.GetProductLineTypeForDDl();
            return View("AddProductLine", model);
        }


        public ActionResult AddProductLine1(string ProductLineDesc, int ProductLineType, string Copyright)
        {
            objTreeViewDal = new TreeViewDal();
            ProductModel model = new ProductModel();
            model.strProductLineDesc = ProductLineDesc;
            model.intProductLineTypeId = ProductLineType;
            model.CopyrightDesc = Copyright;

            objTreeViewDal.SetProductLine(ref model);
            model.LstProductLineTypeModel = objTreeViewDal.GetProductLineTypeForDDl();
            if (model.intProductLineId > 0)
            {
                model.intProductLineTypeId = 0;
                model.strProductLineDesc = "";
                model.CopyrightDesc = "";
            }


            return View("AddProductLine", model);
        }


        [HttpPost]
        public ActionResult AddProductLine(ProductModel model)
        {
            objTreeViewDal = new TreeViewDal();
            objTreeViewDal.SetProductLine(ref model);
            model.LstProductLineTypeModel = objTreeViewDal.GetProductLineTypeForDDl();
            if (model.intProductLineId > 0)
            {
                model.intProductLineTypeId = 0;
                model.strProductLineDesc = "";
                model.CopyrightDesc = "";
            }


            return View("AddProductLine", model);
        }



        //    public ActionResult AddBookWithParam(int ProdLineId, string Desc)
        //  //  public ActionResult AddBookWithParam()    
        //{
        //        BookModel model = new BookModel();

        //        model.strBookTitle = "test mm";
        //        model.intBookId = 1;
        //        return View("AddBookWithParam",model);
        //    }
    }
}

TBScripts/Controllers/SystemAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TBScripts.DAL;
using TBScripts.Models;
using System.IO;
using System.Data.SqlClient;
using System.Data;

using System.Text.RegularExpressions;

namespace TBScripts.Controllers
{
    public class SystemAdminController : BaseController
    {
        // GET: SystemAdmin
        // PHdataConnectionString1 DBContext = new PHdataConnectionString1();
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult SetupSystem()
        {
            return View();
        }

        public ActionResult AddCustomer(int custId)
        {
            CustomerModel model = new CustomerModel();
            if (custId > 0)
            {
                using (TBScripts.DAL.PHdataConnectionString1 DBContext = new TBScripts.DAL.PHdataConnectionString1())
                {

                    var dblocations = DBContext.Customers.Where(location => location.CustomerId == custId).SingleOrDefault();
                    if (dblocations != null)
                    {

                        model.CustomerId = dblocations.CustomerId;
                        model.CustomerName = dblocations.CustomerName;
                        model.Address1 = dblocations.Address1;
                        model.Address3 = dblocations.Address3;
                        model.Address2 = dblocations.Address2;
                        model.City = dblocations.City;
                        model.IsActive = (bool)dblocations.IsActive;
                        model.PostalCode = dblocations.PostalCode;
                        model.StateId = dblocations.StateId;
                        model.Notes = dblocations.Notes;

                    }
                }
            }

            model.StatesList = getListofStates();
            return View(model);
        }
        [HttpPost]
        public ActionResult AddCustomer(CustomerModel model)
        {
            try
            {
                using (TBScripts.DAL.PHdataConnectionString1 DBContext = new TBScripts.DAL.PHdataConnectionString1())
                {
                    if (model.CustomerId > 0)
                    {
                        var dblocations = DBContext.Customers.Where(location => location.CustomerId == model.CustomerId).SingleOrDefault();
                        if (dblocations != null)
                        {
                            //model.CustomerId = dblocations.CustomerId;
                            dblocations.CustomerName = model.CustomerName;
                            dblocations.Address1 = model.Address1;
                            dblocations.Address3 = model.Address3;
                            dblocations.Address2 = model.Address2;
                            dblocations.City = model.City;
                            dblocations.IsActive = model.IsActive;
                            dblocations.PostalCode = model.PostalCode;
                            dblocations.StateId = model.StateId;
                            dblocations.Notes = model.Notes;

                            DBContext.SaveChanges();

                        }
                    }
                    else
                    {
                        Customer AddCust = new Customer();
                        AddCust.CustomerName = model.CustomerName;
                        AddCust.Address2 = model.Address2;
                        AddCust.Address3 = model.Address3;
                        AddCust.City = model.City;
                        AddCust.StateId = model.StateId;
                        AddCust.PostalCode = model.PostalCode;
                        AddCust.Notes = model.Notes;
                        AddCust.Address1 = model.Address1;
                        AddCust.IsActive = model.IsActive;
                        DBContext.Customers.Add(AddCust);
                        DBContext.SaveChanges();
                    }

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("ViewCustomer");
        }

        public ActionResult ViewCustomer()
        {

            List<CustomerModel> lstCustomerModel = new List<CustomerModel>();
            try
            {


                using (TBScripts.DAL.PHdataConnectionString1 DBContext = new TBScripts.DAL.PHdataConnectionString1())
                {

                    var dblocations = DBContext.Customers.Where(location => location.IsActive == true).ToList();
                    foreach (var item in dblocations)
                    {
                        CustomerModel cust = new CustomerModel();
                        cust.CustomerId = item.CustomerId;
                        cust.CustomerName = item.CustomerName;
                        cust.Address1 = item.Address1;
                        cust.Address3 = item.Address3;
                        cust.Address2 = item.Address2;
                        cust.City = item.City;
                        cust.IsActive = (bool)item.IsActive;
                        cust.PostalCode = item.PostalCode;
                        cust.StateId = item.StateId;
                        cust.Notes = item.Notes;
                        lstCustomerModel.Add(cust);
                    }
                }

            }

            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting  
                        // the current instance as InnerException  
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            catch (Exception ex)
            {

                throw ex;
            }



            return View(lstCustomerModel);
        }

        //Get Product line

        public ActionResult ViewProductLine()
        {

            ListProductLineTypeModel ProductLineTypeModel1 = new ListProductLineTypeModel();
            List<ProductLineModel> lstProductLineModel = new List<ProductLineModel>();
            List<ProductLineType> dbProductLineType = new List<ProductLineType>();
            try
            {


                using (TBScripts.DAL.PHdataConnectionString1 DBContext = new TBScripts.DAL.PHdataConnectionString1())
                {

                    // var dblocations = DBContext.ProductLines.Where(location => location.IsActive == true).ToList();
                    var dbProductLine = from s in DBContext.ProductLines
                                        join sa in DBContext.ProductLineTypes
                                        on s.ProductLineTypeId equals sa.ProductLineTypeId
                                        select s;
                    foreach (var item in dbProductLine)
                    {
                        ProductLineModel prod = new ProductLineModel();
                        prod.ProductLineId = item.ProductLineId;
                        prod.ProductLineDesc = item.ProductLineDesc;
                        prod.ProductLineTypeId = (int)item.ProductLineTypeId;
                        prod.strProductLineTypeDesc = item.ProductLineType.ProductLineTypeDesc;
                        prod.CopyrightDesc = item.CopyrightDesc;

                        lstProductLineModel.Add(prod);
                    }

                    dbProductLineType = DBContext.ProductLineTypes.ToList();

                    ProductLineTypeModel1.lstProductLine = lstProductLineModel;
                    ProductLineTypeModel1.lstProductLineType = dbProductLineType;
                }

            }

            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting  
                        // the current instance as InnerException  
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            catch (Exception ex)
            {

                throw ex;
            }



            //return View(lstProductLineModel);
            return View(ProductLineTypeModel1);
        }

        public List<StateModel> getListofStates()
        {
            List<StateModel> StatesList = new List<StateModel>();
            StateModel prod1 = new StateModel();
            prod1.StateId = "";
            prod1.StateName = "Please Select";
            StatesList.Add(prod1);
            try
            {
                using (TBScripts.DAL.PHdataConnectionString1 DBContext = new TBScripts.DAL.PHdataConnectionString1())
                {

                    // var dblocations = DBContext.ProductLines.Where(location => location.IsActive == true).ToList();
                    var dbstates = from s in DBContext.StateProvinces select s;
                    foreach (var item in dbstates)
                    {
                        StateModel prod = new StateModel();

TBScripts/Views/SystemAdmin/AddCustomer.cshtml
@model TBScripts.Models.CustomerModel

@{
    ViewBag.Title = "AddCustomer";
    Layout = "~/Views/Shared/_TBMainLayout.cshtml";
}

@Html.Partial("~/Views/Shared/_TBSystemAdmin.cshtml")

<div class="col-med-5 col-lg-9 row main-right ">
    <div class="panel panel-default systemAdminDiv">

        <div class="MainForm">
            <h2 class="marginTop">Add Customer</h2>




            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @*<h4>CustomerModel</h4>*@
                    <hr />
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(m => m.CustomerId)

                    @*<div class="form-group">
                            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.CustomerId)
                                @Html.ValidationMessageFor(model => model.CustomerId)
                            </div>
                        </div>*@
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label " })
                                </div>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.CustomerName, htmlAttributes: new { @class = "form-control" })

                                    @Html.ValidationMessageFor(model => model.CustomerName, null, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label " })
                                </div>
                                <div class="col-md-8">
                                    @Html.CheckBoxFor(model => model.IsActive)
                                    @Html.ValidationMessageFor(model => model.IsActive)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label " })
                                </div>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.Address1, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Address1, null, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label " })
                                </div>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.Address2, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Address2)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.Address3, htmlAttributes: new { @class = "control-label " })
                                </div>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.Address3, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Address3)
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label " })
                                </div>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.City, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.City, null, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label" })
                                </div>
                                <div class="col-md-8">
                                    @Html.DropDownListFor(model => model.StateId, new SelectList(Model.StatesList, "StateId", "StateName"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StateId, null, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label " })
                                </div>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.PostalCode, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.PostalCode, null, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label " })
                                </div>
                                <div class="col-md-8">
                                    @Html.TextAreaFor(model => model.Notes, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Notes)
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                   &nbsp;
                                </div>
                                <div class="col-md-8 text-right">
                                    <input type="submit" value="Create" class="btn btn-primary btnpadding " />
                                    <input type="button" value="Cancel" class="btn btn-danger btnpadding " onclick="location.href='@Url.Action("ViewCustomer", "SystemAdmin")'" />
                                   
                                </div>


                                
                            </div>
                    </div>
               
                </div>
                    </div>
            }

            @*<div>
                @Html.ActionLink("Back to List", "Index")

            </div>*@

        </div>
    </div>
</div>

TBScripts/Views/SystemAdmin/ViewCustomer.cshtml
@model IEnumerable<TBScripts.Models.CustomerModel>

@{
    ViewBag.Title = "ViewCustomer";
    Layout = "~/Views/Shared/_TBMainLayout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function ($) {
        //  alert('hi');
        $('#example').tablesorter({
            theme: 'blue',
            widthFixed: true,
            // widgets: ['filter']
        }).tablesorterPager({
            // target the pager markup - see the HTML block below
            container: $("#pager"),

            // output string - default is '{page}/{totalPages}';
            // possible variables:
            // {page}, {totalPages}, {startRow}, {endRow} and {totalRows}
            output: '{startRow} to {endRow} ({totalRows})',

            // apply disabled classname to the pager arrows when
            // the rows at either extreme is visible - default is true
            updateArrows: true,

            // remove rows from the table to speed up the sort of large
            // tables. setting this to false, only hides the non-visible rows;
            // needed if you plan to add/remove rows with the pager enabled.
            removeRows: false

        });

        //$("#example").tablesorter({ widthFixed: true, widgets: ['zebra'] }).tablesorterPager({ container: $("#pager") });


    });

    ShowModelPopUp = function () {
        window.showModalDialog('../Home/about', "WindowPopup", 'width=400px,height=400px');
        window
    }



</script>


@Html.Partial("~/Views/Shared/_TBSystemAdmin.cshtml")

<div class="col-med-5 col-lg-9 row main-right ">
    <div class="panel panel-default systemAdminDiv">

        <div class="MainForm">
            <div class="row">
                <div class="col-md-6 col-lg-6">
                    <h2 class="marginTop">Customers</h2>
                </div>
                <div class="col-md-6 col-lg-6 pull-right text-right add-field">
                    <input type="text" placeholder="Search Customer" id="txtSearch" name="txtSearch" />

                    <a href='@Url.Action("AddCustomer", "SystemAdmin",new {custId=0})'>
                        <input type="button" value="Add" id="btnAdd" name="btnAdd" class="btn btn-primary" />
                    </a>
                </div>
            </div>
        </div>
        <div class="form-horizontal">
            <div class="col-md-12 col-lg-12 row main-right ">
                <div class="panel panel-default table-responsive">

                    <table id="example" class="display" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th style="width:5%;"></th>
                                <th>Customer Name</th>
                                <th>IsActive</th>
                                <th>Address</th>
                                <th>City</th>
                                <th>Street</th>
                                <th>Notes</th>

                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                                <th style="width:5%;"></th>
                                <th>Customer Name</th>
                                <th>IsActive</th>
                                <th>Address</th>
                                <th>City</th>
                                <th>Street</th>
                                <th>Notes</th>
                            </tr>
                        </tfoot>

                        <tbody>


                            @foreach (var obj in Model)
                            {
                                <tr>
                                    <td>

                                        <a href='@Url.Action("AddCustomer", "SystemAdmin", new {custId=obj.CustomerId})'>
                                            <input type="image" src="~/Content/pic/images/icon_edit.gif" style="cursor:pointer;" />
                                        </a>

                                        <a href='@Url.Action("AddCustomer", "SystemAdmin", new {custId=obj.CustomerId})'>
                                            <input type="image" src="~/Content/pic/images/icon_delete.gif" style="cursor:pointer;" />
                                        </a>

                                        @*<img src="~/Content/pic/images/icon_edit.gif"
                                            href='@Url.Action("AddCustomer", "SystemAdmin")' style="cursor:pointer;" />*@


                                        @*<img src="~/Content/pic/images/icon_delete.gif" style="cursor:pointer;" />*@
                                    </td>

                                    @*<td>@obj.FolderId</td>
                                        <td>@obj.FolderName</td>*@
                                    @*@Html.TextBoxFor(m => obj.SortSeq, obj.SortSeq)</td>*@



                                    <td>@obj.CustomerName </td>
                                    <td>@obj.IsActive</td>
                                    <td>@obj.Address1</td>
                                    <td>@obj.City</td>
                                    <td>@obj.Address2</td>
                                    <td>@obj.Notes</td>




                                </tr>
                            }



                        </tbody>


                    </table>


                    <div id="pager" class="pager">
                        <form>
                            <img src="http://mottie.github.com/tablesorter/addons/pager/icons/first.png" class="first" />
                            <img src="http://mottie.github.com/tablesorter/addons/pager/icons/prev.png" class="prev" />
                            <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
                            <img src="http://mottie.github.com/tablesorter/addons/pager/icons/next.png" class="next" />
                            <img src="http://mottie.github.com/tablesorter/addons/pager/icons/last.png" class="last" />
                            <select class="pagesize">
                                <option selected="selected" value="10">10</option>

                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                            </select>
                        </form>


                    </div>

                </div>
            </div>
        </div>
    </div>
</div>