TBScripts/Controllers/TreeViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TBScripts.Models;
using TBScripts.DAL;

namespace TBScripts.Controllers
{
    public class TreeViewController : BaseController
    {
        private TreeViewDal objTreeViewDal;
        private TreeViewModel objTreeView;

        //
        // GET: /TreeView/
        public ActionResult Treeview()
        {
            int i = UDTO.siteId;
            TreeViewModel objTreeView = new TreeViewModel();
            List<TreeViewModel> lstTreeView = new List<TreeViewModel>();
            objTreeViewDal = new TreeViewDal();
            lstTreeView = objTreeViewDal.GetTreeView();
            return View(lstTreeView);
        }

        public ActionResult AddToEfolder(int id,string name)
        {

            Mymodel model = new Mymodel();
            model.Id = id;
            model.Name =HttpUtility.UrlDecode(name);
            TreeViewModel objTreeView = new TreeViewModel();
            List<TreeViewModel> lstTreeView = new List<TreeViewModel>();
            objTreeViewDal = new TreeViewDal();
            lstTreeView = objTreeViewDal.GetTreeView();
            model.treeViewModel = lstTreeView;

            if (lstTreeView.Count > 0)
            {
                ProductModel objProductModel = new ProductModel();
                objProductModel.intProductLineId = lstTreeView[0].intProductLineId;
                objProductModel.intlanguageId = 1;
                objTreeViewDal.GetProductLine(ref objProductModel);
                model.ProductModel = objProductModel;
            }
            //getting languages 
            List<LanguageModel> lstLanguage = new List<LanguageModel>();
            lstLanguage = objTreeViewDal.GetLanguages();
            ViewData["Language"] = lstLanguage;

            List<ProductLineTypeModel> lstProductLineType = new List<ProductLineTypeModel>();
            lstProductLineType = objTreeViewDal.GetProductLineType();
            ViewData["ProductLineType"] = lstProductLineType;

            return View(model);

        }

       //[CustomAuthorizeAttribute("Admin")]
        public ActionResult Browse()
        {

            //Dim dt As Data.DataTable
            //dt = Helper.DB.ProcedureTable("FillLanguage", 0)

            Mymodel model = new Mymodel();
            TreeViewModel objTreeView = new TreeViewModel();
            List<TreeViewModel> lstTreeView = new List<TreeViewModel>();
            objTreeViewDal = new TreeViewDal();
            lstTreeView = objTreeViewDal.GetTreeView();
            model.treeViewModel = lstTreeView;

            if (lstTreeView.Count > 0)
            {
                ProductModel objProductModel = new ProductModel();
                objProductModel.intProductLineId = lstTreeView[0].intProductLineId;
                objProductModel.intlanguageId = 1;
                objTreeViewDal.GetProductLine(ref objProductModel);

                //objProductModel.strProductLineDesc = "Teaching Book";
                //objProductModel.intProductLineTypeId = 2;
                //objProductModel.strProductLineTypeDesc = "3-Tier(no chapters)";
                //objProductModel.CopyrightDesc = "2007";

                model.ProductModel = objProductModel;
            }
            //getting languages 
            List<LanguageModel> lstLanguage = new List<LanguageModel>();
            lstLanguage = objTreeViewDal.GetLanguages();
            ViewData["Language"] = lstLanguage;
            //List<SelectListItem> li = new List<SelectListItem>();
            //li.Add(new SelectListItem { Text = "Select", Value = "0" });
            //  ViewData["Language"] = new SelectList(lstLanguage, "intlanguageId", "strlanguageName");
            // ViewData["Language"] = lstLanguage;

            //getting languages 
            List<ProductLineTypeModel> lstProductLineType = new List<ProductLineTypeModel>();
            lstProductLineType = objTreeViewDal.GetProductLineType();
            // ViewData["ProductLineType"] = new SelectList(lstProductLineType, "intProductLineTypeId", "strProductLineTypeDesc");
            ViewData["ProductLineType"] = lstProductLineType;

           // TempData["BooksItems"] = lstTreeView;


            return View(model);
        }

        public ActionResult Browse2(int? lintBookId)
        {
            Mymodel model = new Mymodel();
            TreeViewModel objTreeView = new TreeViewModel();
            List<TreeViewModel> lstTreeView = new List<TreeViewModel>();
            objTreeViewDal = new TreeViewDal();
            lstTreeView = objTreeViewDal.GetTreeViewByBookId(lintBookId);
            model.treeViewModel = lstTreeView;

            //BookModel objBook = new BookModel();
            //objBook.intBookId = (int)lintBookId;
            //objTreeViewDal.GetBookByBookId(ref objBook);
            //ViewData["Book"] = objBook;

            //getting Product Line 
            //List<ProductLineModel> lstProductLine = new List<ProductLineModel>();
            //lstProductLine = objTreeViewDal.GetProductLine();
            //ViewData["ProductLine"] = lstProductLine;


           // Mymodel model1 = new Mymodel();
            TreeViewModel objTreeView1 = new TreeViewModel();
            List<TreeViewModel> lstTreeView1 = new List<TreeViewModel>();
            lstTreeView1 = objTreeViewDal.GetTreeView();
           // model1.treeViewModel = lstTreeView1;
            //needs write loop here

            int lintPrvBookId = 0;
            List<TreeViewModel> t = new List<TreeViewModel>();
            foreach (var book in lstTreeView1)
            {
                if (book.intBookId != lintPrvBookId)
                {
                    t.Add(book);
                }
                lintPrvBookId = book.intBookId;
            }

            TempData["BooksItems"] = t;

            return View(model);
        }

        [ValidateInput(false)]
        public JsonResult Browse3(int? lintBookId)
        {
            Mymodel model = new Mymodel();
            TreeViewModel objTreeView = new TreeViewModel();
            List<TreeViewModel> lstTreeView = new List<TreeViewModel>();
            objTreeViewDal = new TreeViewDal();
            lstTreeView = objTreeViewDal.GetTreeViewByBookId(lintBookId);
            model.treeViewModel = lstTreeView;
            // return View(model);
            // var id = Ifbp.InsertingFormFields(formId, formFields);

            //BookModel objBook = new BookModel();
            //objBook.intBookId = (int)lintBookId;
            //objTreeViewDal.GetBookByBookId(ref objBook);
            //ViewData["Book"] = objBook;

            //ViewData["sudha"] = "sudhakar";

            ////getting Product Line 
            //List<ProductLineModel> lstProductLine = new List<ProductLineModel>();
            //lstProductLine = objTreeViewDal.GetProductLine();
            //ViewData["ProductLine"] = lstProductLine;


            // Mymodel model1 = new Mymodel();
            TreeViewModel objTreeView1 = new TreeViewModel();
            List<TreeViewModel> lstTreeView1 = new List<TreeViewModel>();
            lstTreeView1 = objTreeViewDal.GetTreeView();
            // model1.treeViewModel = lstTreeView1;
            //needs write loop here

            int lintPrvBookId = 0;
            List<TreeViewModel> t = new List<TreeViewModel>();
            foreach (var book in lstTreeView1)
            {
                if (book.intBookId != lintPrvBookId)
                {
                    t.Add(book);
                }
                lintPrvBookId = book.intBookId;
            }

            TempData["BooksItems"] = t;

            return Json(lstTreeView, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LoadCountries()
        {

            List<SelectListItem> li = new List<SelectListItem>();

            li.Add(new SelectListItem { Text = "Select", Value = "0" });

            li.Add(new SelectListItem { Text = "India", Value = "1" });

            li.Add(new SelectListItem { Text = "Srilanka", Value = "2" });

            li.Add(new SelectListItem { Text = "China", Value = "3" });

            li.Add(new SelectListItem { Text = "Austrila", Value = "4" });

            li.Add(new SelectListItem { Text = "USA", Value = "5" });

            li.Add(new SelectListItem { Text = "UK", Value = "6" });

            ViewData["country"] = li;

            return View();
        }


       
    }
}

TBScripts/Views/Shared/_AddCoverSheetPartial.cshtml
@model TBScripts.DAL.FileCoversheet

<script src="@Url.Content("~/Scripts/tinymce/tinymce.js")" type="text/javascript"></script>


<style type="text/css">
    .notescontent {
        display: block;
        margin-left: 6px;
        margin-bottom: 10px;
        float: left;
        width: 57%;
    }
</style>

<script type="text/javascript">
    $(document).ready(function ($) {
        (function () {
            tinymce.init({
                mode: "exact",
                elements: "text", //ID for textarea
                //  mode: "textareas",
                // elements: "@ViewData.TemplateInfo.GetFullHtmlFieldId(string.Empty)",
                theme: "modern",
                height: 200,
                width: 600,
                plugins: [
                    "  advlist autolink lists link image charmap print preview hr anchor pagebreak",
                    "searchreplace wordcount visualblocks visualchars code fullscreen",
                    "insertdatetime media nonbreaking save table contextmenu directionality",
                    "emoticons template paste textcolor"
                ],
                toolbar1: " insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
                toolbar2: "print preview media | forecolor backcolor emoticons",
                image_advtab: true,
                templates: [
                    { title: 'pre start', content: '<pre><code>' },
                    { title: 'pre end', content: '</code></pre>' }
                ]
            });
        })();

    });

    function UpdateNotes()
    {
        debugger;

        id = 2003;
        name = "test";
        alert("test_su");

        var x = document.getElementById("ifr1");
        //x.setAttribute("src", "http://www.w3schools.com");
        //x.setAttribute("src", "/FolderView/PrintFile?lintBookId=" + id + "&strBookName=" + encodeURI(name) + "");

        var serviceURL = ""
        var serviceURL = '@Url.Action("AddNoteDetails", "FolderView")';

        var lintIdValue = $("#Id").val();
        var lintFileIdValue = $("#FileId").val();
        var lintsiteidValue = $("#SiteId").val();
        var strDescriptionValue = $("#Description").val();
        var strtextValue = tinymce.get("Text").getContent();
        alert(strtextValue);

        if (strtextValue == '' || strtextValue == null) {
            alert('Please enter notes ');
            return false;
        }

        $.ajax({
            type: "POST",
            url: serviceURL,
            data: { lintId: lintIdValue, lintFileId: lintFileIdValue, lintsiteid: lintsiteidValue, strDescription: strDescriptionValue, strtext: strtextValue }
        }).done(function (data) {
            //alert(data);
            successFunc(data, status);

        }).error(function () {
            alert('Error');
        });


        function successFunc(data, status) {
            alert("Notes added successfully");
            // $("#strBookTitle").val('');
        }

        function errorFunc() {
            alert('error');
        }


        //window.frames["ifr1"].focus();
        //window.frames["ifr1"].print();

    }
</script>

<div style="border-bottom: 1px solid #ccc;display: inline-block;margin-bottom: 20px;padding: 15px 0;width: 100%;">

    <div style="float:left; width:80%;">
        <img src="../Images/PH/icon_show_table_big.gif" width="32" height="32"><strong>Add Coversheet</strong>

    </div>
   
</div>



<div style="clear:both"></div>
<div class="notescontent">
    <div class="content1-sub">
       
        Patient Name:
    </div>
    <div style="float:left;width:30%">
        @Html.EditorFor(model => model.name)
       
    </div>
</div>

<div style="clear:both"></div>
<div class="notescontent">
    <div class="content1-sub">
       Coversheet Text :
    </div>
    <div style="float:left;width:30%">
        @Html.EditorFor(model => model.text, new { @class = "test" })
      
    </div>
</div>


<div style="clear:both"></div>
<div class="notescontent">
    <div class="content1-sub">
        &nbsp;
    </div>
    <div style="float:left;width:30%">
     
        <input type="button" value="Print" id="btnPrint" name="btnPrint" class="btn btn-primary" onclick="UpdateNotes();" /> &nbsp;
        @*<input type="button" value="Cancel" id="btnCancel" name="btnCancel" class="btn btn-primary" onclick="gobackViewContert();" />*@
    </div>
</div>

TBScripts/Views/Shared/_AddFolderPartial.cshtml
@*@model List<TBScripts.Models.TreeViewModel>*@
@model TBScripts.Models.Mymodel
@using TBScripts.Models;

<link href="~/Content/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link href="~/Content/css/tbcustom2.css" rel="stylesheet" media="screen">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">


@{
    int lintPrvBookId = 0;
    Mymodel m = new Mymodel();
    List<TreeViewModel> t = new List<TreeViewModel>();
    t = Model.treeViewModel;
  


    <div class="col-med-2 col-lg-2 navtree" style="width:200px; height:360px;overflow-x:hidden;overflow-y:auto">

        <div class="list-group" style="width:200px;">
            <a href="#" class="list-group-item active">
                <span class="glyphicon glyphicon-book"></span> The Teaching Book <span class="badge"></span>
            </a>
            @foreach (var book in t)  
            {
                if (book.intBookId != lintPrvBookId)
                {
                    <a class="list-group-item" href=@Url.Action("Browse2", "TreeView", new { lintBookId = book.intBookId}) >
                      
                        <span class="glyphicon glyphicon-file"></span>@book.strBookTitle
                    </a>
                    if (book.intSiteId > 0)
                    {

                        <a class="list-group-item" href=@Url.Action("Browse2", "TreeView", new { lintBookId = book.intBookId}) >
                         
                            <span class="glyphicon glyphicon-file" style="margin-left:10px;"></span>@book.strSectionTitle@*<span class="badge">##</span>*@
                        </a>
                    }
                   
                }
                else
                {
                    if (book.intSiteId > 0)
                    {

                        <a class="list-group-item" href=@Url.Action("Browse2", "TreeView", new { lintBookId = book.intBookId})>
                         
                            <span class="glyphicon glyphicon-file" style="margin-left:10px;"></span>@book.strSectionTitle@*<span class="badge">##</span>*@
                        </a>
                    }
                }
                lintPrvBookId = book.intBookId;
            }
          
        </div>
    </div>

    <div>
        <br />
        <strong>Selected File:</strong>
        @Model.Name<br>
        <br>
        Please select a Folder from the tree on the left. After highlighting the
        folder, click the "Add" button to link the selected file to the folder.
        <br>
        <br>
        Click "Cancel" to close this dialog without linking the file.
        <br />
        <input name="cmdSubmit" type="button" class="button_medium" value="Add">
        <input name="cmdCancel" type="button" class="button_medium" value="Cancel">

    </div>

}

TBScripts/Views/Shared/_AddSiteBookPartial.cshtml
@model TBScripts.Models.SiteBookModel



<script>
    //this code goes in your partialview
    $(function () {
        //allow the validation framework to re-prase the DOM
        jQuery.validator.unobtrusive.parse();

        //or to give the parser some context, supply it with a selector
        //jQuery validator will parse all child elements (deep) starting
        //from the selector element supplied
        jQuery.validator.unobtrusive.parse("#saveSiteBook");
    });


    $(function () {
        $("#BookId").change(function () {
            var selValue = $(this).find(":selected").val();
            if (selValue) {
                var TeamDetailPostBackURL = '/SystemAdmin/IsBookExistForSite';
                debugger;
           
                var siteId = $('#hdnSited').val();
             
                $.ajax({
                    type: "GET",
                    url: TeamDetailPostBackURL,
                    contentType: "application/json; charset=utf-8",
                    data: { "SiteId": siteId, "BookId": selValue },
                    datatype: "json",
                    success: function (data) {
                        debugger;
                        if (data > 0) {
                            alert("Already exist,please select another book");
                         
                            $("#btnSubmit").attr("disabled", "disabled");
                        }
                        else {
                            $("#btnSubmit").removeAttr("disabled");
                        }
                       
                      
                    },
                    error: function () {
                       alert("Dynamic content load failed.");
                        
                    }
                });
            }
           
        })

    });

</script>

@using (Html.BeginForm("PartialViewAddSiteBooks", "SystemAdmin", FormMethod.Post, new { @id = "saveSiteBook" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">


        @Html.HiddenFor(m => m.SiteId)
        @Html.HiddenFor(model => model.OldBookId)
        @Html.HiddenFor(model => model.SiteName)



        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-4">
                        @*@Html.LabelFor(model => model.BookTitle, htmlAttributes: new { @class = "control-label " })*@
                        <span class="control-label">Book</span>
                    </div>
                    <div class="col-md-8">
                        @*@Html.TextBoxFor(model => model.SectionTitle, htmlAttributes: new { @class = "form-control" })*@

                        @Html.DropDownListFor(model => model.BookId, new SelectList(Model.Books, "BookId", "BookTitle"), "--- Select ---", new { @class = "form-control" })

                        @Html.ValidationMessageFor(model => model.BookId, null, new { @class = "text-danger" })

                        @*@Html.ValidationMessageFor(model => model.SectionTitle, null, new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>
        </div>



      

        <div class="modal-footer">
            <button type="button" id="btncancel" class="btn btn-danger" data-dismiss="modal">Close</button>
            <input type="submit" id="btnSubmit" name="btnSubmit" value="Save" class="btn btn-primary" />
        </div>


    </div>
}

TBScripts/Views/Shared/_CoversheetPartial.cshtml
@model List<TBScripts.DAL.FileCoversheet>



<link href="@Url.Content("~/JsTableSorter/theme.blue.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/JsTableSorter/jquery.tablesorter.js")" type="text/javascript"></script>
<script src="@Url.Content("~/JsTableSorter/jquery.tablesorter.pager.js")" type="text/javascript"></script>
<script src="@Url.Content("~/JsTableSorter/jquery.tablesorter.widgets.js")" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function ($) {
        //  alert('hi');
        $('#example').tablesorter({
            theme: 'blue',
            widthFixed: true,
            // widgets: ['filter']
        }).tablesorterPager({
            // target the pager markup - see the HTML block below
            container: $("#pager"),

            // output string - default is '{page}/{totalPages}';
            // possible variables:
            // {page}, {totalPages}, {startRow}, {endRow} and {totalRows}
            output: '{startRow} to {endRow} ({totalRows})',

            // apply disabled classname to the pager arrows when
            // the rows at either extreme is visible - default is true
            updateArrows: true,

            // remove rows from the table to speed up the sort of large
            // tables. setting this to false, only hides the non-visible rows;
            // needed if you plan to add/remove rows with the pager enabled.
            removeRows: false

        });

        //$("#example").tablesorter({ widthFixed: true, widgets: ['zebra'] }).tablesorterPager({ container: $("#pager") });


    });
</script>


<div style="border-bottom: 1px solid #ccc;display: inline-block;margin-bottom: 20px;padding: 15px 0;width: 100%;">

    <div style="float:left; width:80%;">
        <img src="../Images/PH/icon_show_table_big.gif" width="32" height="32"><strong>Previously Printed Coversheets </strong>

    </div>
    @*<div style="float:left; width:20%; text-align:right;">
            <input type="button" name="btnAddNote" id="btnAddNote" value="Add Note">
        </div>*@



</div>

<table id="example" class="display" width="100%" cellspacing="0">
    <thead>
        <tr width="100%" >
            <th style="text-align:center;">Coversheet Text </th>
        </tr>
    </thead>


    <tbody>


        @foreach (var obj in Model)
            {
                <tr>
                    
                    <td>@obj.text</td>

                </tr>
            }

       

    </tbody>


</table>

TBScripts/Views/Shared/_PDFPartial.cshtml
@model TBScripts.Models.PDFViewModel



<script type="text/javascript">


    function ContentView(handoutId,handoutName) {


        $("#divNotes").css("display", "none");
        $("#divContent").css("display", "block");
        $("#divCoversheet").css("display", "none");

        var id = handoutId;
        var name = handoutName

        var url = "@Url.Action("ReturnPartial", "FolderView")";
        //alert(id);
      
        $.ajax({
            type: "POST",
            url: url,
            data: { lintBookId: id,strBookName:name },

            success: successFunc1,
            error: errorFunc1
        });

        function successFunc1(data, status) {
             
            $('#Browse2Tabs').html('');
            $("#Browse2Tabs").tabs();
            $('#Browse2Tabs').html(data);

            //alert(data);
            
        }
        function errorFunc1() {
            alert('error');
        }

    }

    function NotesView(handoutId) {


        $("#divNotes").css("display", "block");
        $("#divContent").css("display", "none");
        $("#divCoversheet").css("display", "none");

        var id = handoutId;

        var url = "@Url.Action("ReturnNotesPartial", "FolderView")";


        $.ajax({
            type: "POST",
            url: url,
            data: { lintBookId: id},

            success: successFunc1,
            error: errorFunc1
        });

        function successFunc1(data, status) {

            $('#divNotes').html('');
            $("#divNotes").tabs();
            $('#divNotes').html(data);

            //alert(data);

        }
        function errorFunc1() {
            alert('error');
        }

    }

    function CoversheetView() {


        $("#divNotes").css("display", "none");
        $("#divContent").css("display", "none");
        $("#divCoversheet").css("display", "block");



        var url = "@Url.Action("ReturnCoverSheetPartial", "FolderView")";
        alert("sudhakar");

        $.ajax({
            type: "POST",
            url: url,
            success: successFunc1,
            error: errorFunc1
        });

        function successFunc1(data, status) {

            $('#divCoversheet').html('');
            $("#divCoversheet").tabs();
            $('#divCoversheet').html(data);

            //alert(data);

        }
        function errorFunc1() {
            alert('error');
        }

    }


    $(document).ready(function () {


        //$(function () {
        //    $("#liViewContent").on("click", function () {

        //        $("#divNotes").css("display", "none");
        //        $("#divContent").css("display", "block");
        //        $("#divCoversheet").css("display", "none");

        //    });
        //});

        @*$(function () {
            $("#liNotes").on("click", function (BookId) {



                $("#divNotes").css("display", "block");
                $("#divContent").css("display", "none");
                $("#divCoversheet").css("display", "none");

                var id = 1;
                var name = 'sudha';
                var url = "@Url.Action("ReturnNotesPartial", "FolderView")";
                alert(id);

                $.ajax({
                    type: "POST",
                    url: url,
                    data: { lintBookId: id,strBookName:name },

                    success: successFunc1,
                    error: errorFunc1
                });

                function successFunc1(data, status) {

                    $('#divNotes').html('');
                    $("#divNotes").tabs();
                    $('#divNotes').html(data);

                    //alert(data);

                }
                function errorFunc1() {
                    alert('error');
                }

            });
        });*@









    });







</script>

<div class="panel panel-default">
    <div class="panel-heading" id="tabs">
        <ul class="nav-main nav-main-tabs" role="tablist">
            <li id="Li-1"><a href="#divContent" id="liViewContent" onclick="ContentView(@Model.Id,'@Model.Name');">View Content</a></li>
            <li id="Li-2"><a href="#divNotes" id="liNotes" onclick="NotesView(@Model.Id);">Notes</a></li>
            <li id="Li-3"><a href="#divCoversheet" id="liCoversheets" onclick="CoversheetView();">Coversheets</a></li>
        </ul>
        <div id="divContent" class="panel-body">

            @Html.Partial("~/Views/Shared/_ViewContentPartial.cshtml", Model)

        </div>



        <div id="divNotes" class="panel-body" style="display:none;">

            @*@Html.Partial("~/Views/Shared/_notesPartial.cshtml")*@

        </div>

        <div id="divCoversheet" class="panel-body" style="display:none;">

            @*@Html.Partial("~/Views/Shared/_coversheetPartial.cshtml")*@

        </div>
    </div>

</div>

TBScripts/Views/Shared/_PDFViewPartial.cshtml
@model TBScripts.Models.PDFViewModel


@*<iframe  style="BORDER-BOTTOM: silver 1px solid; BORDER-LEFT: silver 1px solid; WIDTH: 98%; HEIGHT: 98%; BORDER-TOP: silver 1px solid; BORDER-RIGHT: silver 1px solid"
        src="@Url.Action("GetPDF", "FolderView", new { id = Model.Id })#pagemode=none&amp;toolbar=0&amp;view=FitH"
        name="ifr1" id="ifr1" scrolling=no>
    Your browser do not support frames!
</iframe>*@

TBScripts/Views/Shared/_SectionTabPartial.cshtml
@model TBScripts.Models.SectionModel



<div class="panel panel-default">
    <div class="panel-heading" id="tabs">
        <ul class="nav-main nav-main-tabs" role="tablist">
            <li id="Li-1"><a href="#divViewSection" id="liViewSection">Edit Section</a></li>  @*onclick="EditSection(@Model.SectionId,'@Model.SectionTitle')*@
            <li id="Li-2"><a href="#divChapaters" id="liChapaters" >Chapaters</a></li>
            <li id="Li-3"><a href="#divFiles" id="liFiles">Files</a></li>
        </ul>
        <div id="divViewSection" class="panel-body">
            @*Edit Section*@

            @Html.Partial("~/Views/Shared/_SectionEditPartial.cshtml", Model)

          

        </div>



        <div id="divChapaters" class="panel-body" style="display:none;">

            @*@Html.Partial("~/Views/Shared/_notesPartial.cshtml")*@

            "Edit divChapaters"

        </div>

        <div id="divFiles" class="panel-body" style="display:none;">

            @*@Html.Partial("~/Views/Shared/_coversheetPartial.cshtml")*@

            "Edit Files"

        </div>
    </div>

</div>

TBScripts/Views/Shared/_TBLayout.cshtml
<html>
<head>
    <title>The TEACHING BOOK </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/css/tbcustom2.css" rel="stylesheet" media="screen">

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!--[if lt IE 9]><style>.IePanel{height:400px;}</style><![endif]-->


</head>

<body>
    <div class="container-fluid">
        <!-- header -->
        <div class="row hdr">
            <div class="col-sm-3 col-md-3 col-lg-3 hdr">
                <!-- LOGO IMAGE -->
                <a href="index.html">
                    <img src="~/Content/pic/tb-logo.png" alt="The Teaching Book">
                </a>
                <!-- /LOGO IMAGE -->

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Login", "Login", "Person")</li>
                </ul>
            </div>

            <div class="col-sm-6 col-md-7 col-lg-7 hdr text-right">
                <p>
                    <a href="#" title="">
                        <span class="glyphicon glyphicon-envelope"></span>
                        <strong>teachingbook@p-h.com</strong>
                    </a> &nbsp;&nbsp;|&nbsp;&nbsp;<strong><span class=" glyphicon glyphicon-phone-alt"></span>  800.241.4925 </strong>
                </p>
            </div>
            <div class=" col-sm-3 col-md-2 col-lg-2 hdr text-right">

                <img src="~/Content/pic/basic_top_icons.png" />
            </div>

        </div>
        <!-- site branding N/A on index-->
        <!-- top Tab nav N/A on index-->
        <!--------------- Content --------------------->
        <div class="col-med-12 col-lg-12 home-content ">
            <div class="panel panel-default">
                @*<div class="panel-heading">Login</div>*@
                <div class="panel-body IePanel">

                    @RenderBody()



                </div>
            </div>

            <!--------------- Footer --------------------->
            <div class=" col-lg-12 row footer">
                <ul class="list-inline text-center">
                    <li> &#169; 2014 Pritchett and Hull Assoc, Inc </li>
                    <li>www.p-h.com</li>
                </ul>
                </nav>
            </div>
        </div>
        <!-- end container-fluid -->
    </div>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>

</body>
</html>